adding hero section
sergey221997/shopify-theme-education pull request #1
Opened 2023-08-22 10:42 UTC by sergey221997

2023-08-23 04:02 UTC, MKhakimov requested changes
Should be blocks

2023-08-23 04:02 UTC, MKhakimov commented on sections/hero.liquid
![image](https://github.com/sergey221997/shopify-theme-education/assets/58659215/cf406d5a-eba0-47df-9e8e-0553347c46bb)

2023-08-24 11:11 UTC, AlexBlacksmith commented on sections/hero.liquid
> +  <h3>{{ block.settings.text }}</h3>
Every content part here must be a block

2023-08-24 11:22 UTC, AlexBlacksmith requested changes
Use 'case' operator to resolve which content you need to show according to block type. For example, only one block has setting with 'heading' ID, but you are trying to render it for every block. I can't see the demo but I'm sure there are a lot of empty "h1" tags

2023-08-31 03:36 UTC, AlexBlacksmith commented on sections/hero.liquid
>  {% endfor %}
Cool, but I think we need to have our own wrapper for section content. And use semantic tags for blocks content.

2023-10-09 07:12 UTC, AlexBeskrovniy approved these changes

2023-10-09 09:03 UTC, MKhakimov approved these changes

2023-10-09 13:35 UTC, merged